<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>property_api_err</key>
        <language>en</language>
        <message>The {0} has encountered the following error: {1}</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>james.jose</sys_created_by>
        <sys_created_on>2023-08-01 17:45:40</sys_created_on>
        <sys_customer_update>false</sys_customer_update>
        <sys_id>b6055fcfb754b55011064993bbe2b24d</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>property_api_err</sys_name>
        <sys_package display_value="Manage-Performance-Review" source="x_sisy_manage_pe_0">3e055fcfff54b5503e3a658df92c90a1</sys_package>
        <sys_policy/>
        <sys_replace_on_upgrade>false</sys_replace_on_upgrade>
        <sys_scope display_value="Manage-Performance-Review">3e055fcfff54b5503e3a658df92c90a1</sys_scope>
        <sys_update_name>sys_ui_message_b6055fcfb754b55011064993bbe2b24d</sys_update_name>
        <sys_updated_by>james.jose</sys_updated_by>
        <sys_updated_on>2023-08-01 17:45:40</sys_updated_on>
    </sys_ui_message>
</record_update>
